require("workspaces.school")
require("workspaces.dots")
require("workspaces.default")
-- TODO: make a projects section instead
require("workspaces.term2term")
require("workspaces.coupledcats")
require("workspaces.twizzler")
require("workspaces.cse108")
require("workspaces.cse130")
require("workspaces.writ2")
